apiVersion: apps/v1
kind: Deployment
metadata:
  name: price-predictor-api
  labels:
    app: price-predictor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: price-predictor
  template:
    metadata:
      labels:
        app: price-predictor
    spec:
      containers:
      - name: api-container
        image: ghcr.io/perann/price-predictor-api:latest
        imagePullPolicy: Always
        command: ["pixi", "run", "uvicorn", "package.price_predictor_api:app", "--host", "0.0.0.0", "--port", "8000"]
        ports:
        - containerPort: 8000
        env:
        - name: MLFLOW_TRACKING_URI
          valueFrom:
            secretKeyRef:
              name: mlflow-s3-secrets
              key: MLFLOW_TRACKING_URI
        - name: MLFLOW_TRACKING_USERNAME
          valueFrom:
            secretKeyRef:
              name: mlflow-s3-secrets
              key: MLFLOW_TRACKING_USERNAME
        - name: MLFLOW_TRACKING_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mlflow-s3-secrets
              key: MLFLOW_TRACKING_PASSWORD
        - name: S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: mlflow-s3-secrets
              key: S3_ACCESS_KEY
        - name: S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: mlflow-s3-secrets
              key: S3_SECRET_KEY
        - name: S3_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: mlflow-s3-secrets
              key: S3_ENDPOINT
        - name: S3_SESSION_TOKEN
          valueFrom:
            secretKeyRef:
              name: mlflow-s3-secrets
              key: S3_SESSION_TOKEN
        resources:
          limits:
            cpu: "500m"
            memory: "1Gi"
          requests:
            cpu: "200m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 40
          periodSeconds: 15