apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-price-api
  labels:
    app: flight-price-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flight-price-api
  template:
    metadata:
      labels:
        app: flight-price-api
    spec:
      containers:
      - name: api-container
        image: ghcr.io/perann/price-predictor-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        # Correspondance entre ton code Python et ton secret Kubernetes
        - name: S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: mlflow_s3_secrets
              key: S3_ACCESS_KEY
        - name: S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: mlflow_s3_secrets
              key: S3_SECRET_KEY
        - name: S3_SESSION_TOKEN
          valueFrom:
            secretKeyRef:
              name: mlflow_s3_secrets
              key: S3_SESSION_TOKEN
        - name: S3_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: mlflow_s3_secrets
              key: S3_ENDPOINT
        - name: MLFLOW_TRACKING_URI
          valueFrom:
            secretKeyRef:
              name: mlflow_s3_secrets
              key: MLFLOW_TRACKING_URI
        - name: MLFLOW_TRACKING_USERNAME
          valueFrom:
            secretKeyRef:
              name: mlflow_s3_secrets
              key: MLFLOW_TRACKING_USERNAME
        - name: MLFLOW_TRACKING_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mlflow_s3_secrets
              key: MLFLOW_TRACKING_PASSWORD
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
          requests:
            cpu: "0.5"
            memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: flight-price-api-service
spec:
  selector:
    app: flight-price-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flight-price-api-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: flight-price-api.lab.sspcloud.fr  
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flight-price-api-service
            port:
              number: 80